### ISSUE TITLE
为何mse会不如感知loss?

### ISSUE THREAD

**Issue by lishiyuwhu** [VITA-Group/GAN-Slimming#2]
看了论文和gs.py,  给我的感觉是是基于cyclegan生成的图像, 外加剪枝loss重新训练一个pix2pix的G. 我这样的理解有问题吗?

既然是衡量student_output_img和teacher_output_img的差距, 为什么感知loss是强于mse的呢? 
我的理解是训练目标就单纯是让G_p2p(student)的结果拟合G_cyclegan(teacher)的结果, mse这样直接的约束为何没有感知loss这样更加偏向语义的约束效果好呢?

**Comment by htwang14** [comment]
Hi, thanks for your interest in our work!  MSE loss mainly focuses on pixel-wise differences, ignoring global content and style features which are more desired in style transfer tasks. In contrast, perceptual is better at capturing global content and style features. Please refer to the original perceptual loss [paper](https://arxiv.org/abs/1603.08155) for more details.
